# Generated by Django 4.0.10 on 2023-10-29 05:49

from django.db import migrations, models

def set_initial_weights(apps, schema_editor):
    PsychometricWeights = apps.get_model('apps', 'PsychometricWeights')
    default_weights = {
        'general': 10.00,
        'reading': 10.00,
        'verbal': 10.00,
        'number': 15.00,
        'numerical': 20.00,
        'spatial': 10.00,
        'nonverbal': 10.00,
        'checking': 10.00,
        'personal': 5.00,
    }

    PsychometricWeights.objects.create(**default_weights)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PsychometricWeights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('reading', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('verbal', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('number', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('numerical', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('nonverbal', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('checking', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('spatial', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('personal', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.RunPython(set_initial_weights)
    ]
